apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.9
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elastic.mydomain.com"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "443"
        resources:
          requests:
            cpu: 0.2
            memory: 256Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      hostAliases:
      - ip: 10.1.1.90
        hostnames:
        - elastic.mydomain.com
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      ##removed because we do not remove logs from masters and ingresses in this ds. Ingress has its own ds
      ##tolerations:
      ##- key: node-role.kubernetes.io/master
        ##operator: Exists
        ##effect: NoSchedule
      ##- operator: "Exists"
      ##  effect: "NoExecute"
      ##- operator: "Exists"
        ##effect: "NoSchedule"
