apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-nginx
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging-nginx
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging-nginx
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging-nginx
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.7
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elastic.mydomain.com"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "443"
        resources:
          requests:
            cpu: 0.01
            memory: 256Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config-nginx
          mountPath: /fluent-bit/etc/
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/containerd/io.containerd.grpc.v1.cri/containers
      - name: fluent-bit-config-nginx
        configMap:
          name: fluent-bit-config-nginx
      serviceAccountName: fluent-bit
      nodeSelector:
        node-role.kubernetes.io/ingress: ''
      tolerations:
        - key: node-role.kubernetes.io/ingress
          operator: Exists
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/network-unavailable
          operator: Exists
          effect: NoSchedule
